.PHONY: build-linter run-linter clean-linter lint run

build-linter:
	@echo "Building staticlint..."
	go build -o staticlint ./cmd/staticlint

run-linter: build-linter
	@echo "Running staticlint with go vet..."
	-go vet -vettool=./staticlint ./cmd/shortener/... ./internal/...

clean-linter:
	@echo "Cleaning up..."
	rm -f staticlint

lint: run-linter clean-linter

run:
	@echo "Running shortener..."
	-go run -ldflags "-X main.BuildVersion=v1 -X 'main.BuildTime=$$(date +'%Y/%m/%d %H:%M:%S')' -X 'main.BuildCommit=$$(git rev-parse HEAD)'" ./cmd/shortener -d "postgresql://localhost:5432/postgres?sslmode=disable"
